#!/bin/bash

#definice barev
red='\033[0;31m'
bg_yellow='\033[0;43m'
green='\033[0;32m'
bg_red='\033[0;41m'
bg_green='\033[0;42m'
clear='\033[0m'
black='\033[1;30m'
yellow='\033[0;33m'

# counter pokusu
touch counter
echo 1 >> counter

#nastaveni parametru
MOD=${1:-2}
PROGRAM='dialog'


#print nadpisu
printf "\n${bg_yellow}${black}POKUS %d${clear}" $(wc -l < counter)
if (($MOD == 1)) ; then
    printf "  M STOP\n"
    printf "=%.0s" {1..16} ; echo
elif (($MOD == 2)) ; then
    printf "  M ASSERT\n"
    printf "=%.0s" {1..17} ; echo
else
    printf "  M ALL\n"
    printf "=%.0s" {1..15} ; echo
fi

#kompilace - ukonceni v pripade erroru
g++ -std=c++17 -Wall -g --pedantic -Wno-long-long -O2 $PROGRAM.cpp -o $PROGRAM || exit 1

if (($MOD == 2)) ; then
    printf "${yellow} RUNNING ${clear}... \n"
    ./$PROGRAM && printf "${bg_green}${black}OK${clear}\n" || printf "${bg_red}${black}FAIL${clear}\n"
    #./main > mujout.txt && printf "${bg_green}${black}OK${clear}\n" || printf "${bg_red}${black}FAIL${clear}\n"
    #cat ./mujout.txt
    exit 0
fi

#vstup testcasu
cd sample/

for input in *in.txt; do
        cislosouboru=${input%_*}
        ../main < $input > ../"$cislosouboru"_mujout.txt
    printf "${yellow} $cislosouboru ${clear}....... "

        if ! diff "$cislosouboru"_out.txt ../"$cislosouboru"_mujout.txt &>/dev/null ; then #pokud chyba
                printf "${bg_red}${black}FAIL${clear}\n"
        printf "=%.0s" {1..100} ; echo #div
                diff -y ../"$cislosouboru"_mujout.txt "$cislosouboru"_out.txt  2>/dev/null
                printf "=%.0s" {1..100} ; echo #div
                if (($MOD == 1)) ; then #pokud je parametr 1, pak zastaveno u chyby
                        break
                fi

        else
                printf "${bg_green}${black}OK${clear}\n" #ok
        fi
done

echo

exit 0